import { describe, it, expect } from "vitest";
import { PAYMENT_PROVIDERS, getPaymentProvider } from "./paymentProviders";

const mgurush = getPaymentProvider("mgurush")!;
const mtnMomo = getPaymentProvider("mtn_momo")!;
const card = getPaymentProvider("visa_mastercard")!;

describe("getPaymentProvider", () => {
  it("returns each registered provider by id", () => {
    expect(mgurush.id).toBe("mgurush");
    expect(mtnMomo.id).toBe("mtn_momo");
    expect(card.id).toBe("visa_mastercard");
  });

  it("returns undefined for an unknown provider id", () => {
    expect(getPaymentProvider("paypal")).toBeUndefined();
  });

  it("registers exactly the three known providers", () => {
    expect(PAYMENT_PROVIDERS.map((p) => p.id).sort()).toEqual(["mgurush", "mtn_momo", "visa_mastercard"]);
  });
});

describe("mobile money providers (m-Gurush / MTN MoMo)", () => {
  it("accepts a plausible phone number and returns a provider-prefixed reference", async () => {
    const result = await mgurush.charge({ phone: "+211912345678", amount: 100, currency: "SSP" });
    expect(result.success).toBe(true);
    if (result.success) expect(result.reference).toMatch(/^MGURUSH-SIM-/);
  });

  it("accepts a phone number with spaces", async () => {
    const result = await mtnMomo.charge({ phone: "+211 912 345 678", amount: 100, currency: "SSP" });
    expect(result.success).toBe(true);
  });

  it("rejects a phone number that's too short", async () => {
    const result = await mgurush.charge({ phone: "12345", amount: 100, currency: "SSP" });
    expect(result.success).toBe(false);
  });

  it("rejects a phone number with letters", async () => {
    const result = await mgurush.charge({ phone: "+211abc345678", amount: 100, currency: "SSP" });
    expect(result.success).toBe(false);
  });

  it("rejects an empty phone number", async () => {
    const result = await mgurush.charge({ phone: "", amount: 100, currency: "SSP" });
    expect(result.success).toBe(false);
  });
});

// S09-12 gap-check (2026-09-15): this simulation no longer accepts any
// card data at all (number/expiry/CVV) — a real-looking card form with no
// real processor behind it is exactly the shape of thing a user might
// reflexively type a real card into. cardLast4/cardBrand are now
// synthetic, generated by the provider itself, never derived from
// anything a caller passes in. See paymentProviders.ts's module comment.
describe("card provider (Visa/Mastercard)", () => {
  it("always succeeds — no card data is accepted or required", async () => {
    const result = await card.charge({ phone: "", amount: 100, currency: "SSP" });
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.reference).toMatch(/^CARD-SIM-/);
      expect(result.cardLast4).toMatch(/^\d{4}$/);
      expect(["Visa", "Mastercard"]).toContain(result.cardBrand);
    }
  });
});
