// A curated starting vocabulary for skill/profession autocomplete — not an
// enforced enum, either here. Users can still type anything; these are
// just suggestions. Deliberately English-only in both lists, matching how
// employer-written and other free-text site content is treated — these
// are suggestion words, not interface copy, so they're outside the i18n
// pipeline (tools/i18n/extract-app-strings.mjs only picks up t()/msg()
// calls, never plain array literals like this file).
export const SKILL_SUGGESTIONS: string[] = [
  // Creative & media
  "Graphic design",
  "Brand identity",
  "Illustration",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere Pro",
  "Photography",
  "Event photography",
  "Videography",
  "Video production",
  "Video editing",
  "Motion graphics",
  "Animation",
  "2D animation",
  "3D modelling",
  "Copywriting",
  "Content writing",
  "Technical writing",
  "Grant writing",
  "Social media content",
  "Podcast editing",
  "Voiceover",
  "Sound engineering",
  "Music production",
  "Signage & print design",
  "Packaging design",

  // Digital & technology
  "Web development",
  "Frontend development",
  "Backend development",
  "Full-stack development",
  "WordPress",
  "Shopify",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "Mobile app development",
  "Android development",
  "iOS development",
  "UI/UX design",
  "Product design",
  "Database administration",
  "Data analysis",
  "Data entry",
  "Data visualisation",
  "Dashboards",
  "GIS / mapping",
  "Digital advertising",
  "Social media management",
  "Email marketing",
  "SEO",
  "Marketing analytics",
  "IT support",
  "Network administration",
  "Systems administration",
  "Cybersecurity",
  "Software development",
  "QA / testing",
  "DevOps",
  "Cloud infrastructure",

  // Business & project support
  "Virtual assistance",
  "Bookkeeping",
  "Accounting",
  "Financial analysis",
  "Audit support",
  "Payroll administration",
  "Research",
  "Market research",
  "Enumeration / field data collection",
  "Survey design",
  "Transcription",
  "Translation",
  "Interpretation",
  "Proofreading",
  "Editing",
  "Project administration",
  "Programme management",
  "Monitoring & evaluation",
  "Report writing",
  "Scheduling",
  "Customer support",
  "Call centre support",
  "Procurement support",
  "Supply chain coordination",
  "Logistics coordination",
  "Warehouse management",
  "Inventory management",
  "Fleet management",
  "Driving",
  "Human resources",
  "Recruitment",
  "Training & facilitation",
  "Community outreach",
  "Security management",
  "Occupational health & safety",
  "Construction supervision",
  "Carpentry",
  "Electrical installation",
  "Plumbing",
  "Welding",
  "Masonry",
  "Solar installation",
  "Mechanical repair",
  "Agricultural extension",
  "Agronomy",
  "Veterinary support",
  "Nursing",
  "Public health",
  "Laboratory technician",
  "Teaching",
  "Curriculum development",
  "Legal support",
  "Contract drafting",
  "Hospitality management",
  "Event planning",
  "Catering",
  "Cleaning & facilities",
];

/**
 * Noun-phrase job titles, for the one-at-a-time "what's your profession /
 * what's this role" fields (ProfessionInput) — distinct from
 * SKILL_SUGGESTIONS' capability phrasing ("Graphic design") since a title
 * reads more naturally as a role ("Graphic designer").
 */
export const PROFESSION_SUGGESTIONS: string[] = [
  // Creative & media
  "Graphic designer",
  "Brand designer",
  "Illustrator",
  "Photographer",
  "Videographer",
  "Video editor",
  "Motion graphics artist",
  "Animator",
  "Copywriter",
  "Content writer",
  "Social media content creator",
  "Podcast producer",
  "Voiceover artist",
  "Sound engineer",
  "Musician",

  // Digital & technology
  "Web developer",
  "Frontend developer",
  "Backend developer",
  "Full-stack developer",
  "Mobile app developer",
  "UI/UX designer",
  "Product designer",
  "Data analyst",
  "Data entry clerk",
  "Database administrator",
  "GIS specialist",
  "Digital marketer",
  "Social media manager",
  "SEO specialist",
  "IT support technician",
  "Network administrator",
  "Systems administrator",
  "Software developer",
  "QA tester",
  "DevOps engineer",

  // Business & project support
  "Virtual assistant",
  "Bookkeeper",
  "Accountant",
  "Financial analyst",
  "Auditor",
  "Payroll administrator",
  "Researcher",
  "Enumerator / field data collector",
  "Survey designer",
  "Transcriptionist",
  "Translator",
  "Interpreter",
  "Proofreader",
  "Editor",
  "Project administrator",
  "Programme manager",
  "Monitoring & evaluation officer",
  "Customer support agent",
  "Call centre agent",
  "Procurement officer",
  "Supply chain coordinator",
  "Logistics coordinator",
  "Warehouse manager",
  "Fleet manager",
  "Driver",
  "HR officer",
  "Recruiter",
  "Trainer / facilitator",
  "Community outreach officer",
  "Security officer",
  "Health & safety officer",
  "Construction supervisor",
  "Carpenter",
  "Electrician",
  "Plumber",
  "Welder",
  "Mason",
  "Solar technician",
  "Mechanic",
  "Agricultural extension officer",
  "Agronomist",
  "Veterinary assistant",
  "Nurse",
  "Public health officer",
  "Laboratory technician",
  "Teacher",
  "Curriculum developer",
  "Legal assistant",
  "Hospitality manager",
  "Event planner",
  "Caterer",
  "Facilities / cleaning supervisor",
];
